In [53]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import time
from tqdm import tqdm_notebook as tqdm

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from matplotlib import font_manager, rc
font_name = font_manager.FontProperties(fname = 'C:\Windows\Fonts\malgun.ttf').get_name()
rc('font',family=font_name)

import warnings
warnings.filterwarnings('ignore')

In [54]:
perfume = pd.read_csv('perfume.csv')
musinsa = pd.read_csv('musinsa_woman.csv')

In [55]:
perfume

,Unnamed: 0,Unnamed: 1,이름,브랜드,향 설명,가격,평점
0,Best,0,조말론 블랙베리 앤 베이 코롱,조말론,유기농으로 키운 블랙베리의 건강한 맛을 그대로 재현한 베스트셀러,"83,800원",4.8
1,Best,1,산타마리아노벨라 프리지아 50ml,산타마리아노벨라,새하얀 수건을 개어놓은 듯한 고혹적인 비누향기,"103,500원",4.8
2,Best,2,르라보 어나더 13 오 드 퍼퓸 50ml,르라보,바닐라와 동물적인 암브레트 씨드에서 주는 우디한 살내음,"220,000원",5.0
3,Best,3,르라보 상탈 33 오 드 퍼퓸 50ml,르라보,짙은 고동나무와 푸릇한 파피루스가 울창하게 심어져 있는 오스트레일리아의 숲속,"220,000원",4.9
4,Best,4,톰포드 오드우드 오 드 퍼퓸 50ml,톰포드,"오우드의 성숙함을 극대화, 톰포드 클래식 섹시의 정수","265,000원",4.8
...,...,...,...,...,...,...,...
854,Women,331,발렌티노 발렌티나 우먼 오 드 퍼퓸 80ml,발렌티노,첫 데이트에 가장 잘 어울릴 것 같은 여성스러운 향기,"135,000원",4.8
855,Women,332,발렌티노 발렌티나 블러쉬 오 드 퍼퓸 50/80ml,발렌티노,달콤한 체리향과 화사한 로즈의 풍미에 스웨이드의 묵직함을 담아낸 향기,"97,000원",5.0
856,Women,333,바이레도 라튤립 오 드 퍼퓸 50/100ml,바이레도,"촉촉한 튤립을 감싸고 있는 하얀 수건, 청순미의 극치","198,500원",4.8
857,Women,334,바이레도 선데이즈드 오 드 퍼퓸 50/100ml,바이레도,설탕을 버무린 오렌지맛 코튼캔디가 석양에 스르르 녹는향기,"191,750원",4.6
858,Women,335,바이레도 로즈 오브 노 맨즈 랜드 오 드 퍼퓸 50ml,바이레도,"바이레도가 그린 선명한 로즈, 라즈베리 이슬이 차가운 장미를 녹이며 깨어나는 싱그런 향기","198,500원",5.0

In [63]:
musinsa.columns = ['No','브랜드','브랜드1','가격','평점','하트']
musinsa.set_index('No')
musinsa

,No,브랜드,브랜드1,가격,평점,하트
0,0,클린,\n \n ...,"\n93,000원 49,900원\n",4.9,"4,684"
1,1,무신사 스탠다드,\n \n ...,"\n19,900원 16,890원\n",4.8,"2,202"
2,2,레르드사봉,\n \n ...,"\n35,000원 24,900원\n",4.8,"3,514"
3,3,포맨트,\n \n ...,"\n62,000원 51,500원\n",4.8,"3,760"
4,4,클린,\n \n ...,"\n57,000원 33,000원\n",4.9,"2,005"
...,...,...,...,...,...,...
2155,2155,머지,\n \n ...,"\n 14,900원\n ...",NaN,NaN
2156,2156,쓰리씨이,\n \n ...,"\n24,000원 21,600원\n",NaN,NaN
2157,2157,머지,\n \n ...,"\n 12,900원\n ...",NaN,NaN
2158,2158,머지,\n \n ...,"\n 9,800원\n ...",NaN,NaN
2159,2159,바디홀릭,\n \n ...,"\n 13,800원\n ...",NaN,NaN

In [52]:
for i in range(len(musinsa.iloc[:,1]):
    print()

No
0                 \n93,000원 49,900원\n
1                 \n19,900원 16,890원\n
2                 \n35,000원 24,900원\n
3                 \n62,000원 51,500원\n
4                 \n57,000원 33,000원\n
                              ...
2155    \n                         14,900원\n          ...
2156              \n24,000원 21,600원\n
2157    \n                         12,900원\n          ...
2158    \n                         9,800원\n           ...
2159    \n                         13,800원\n          ...
Name: 가격, Length: 2160, dtype: object